from __future__ import annotations

from __future__ import annotations

from pathlib import Path

FAST_LOOP_INTERVAL_MINUTES = 15
CALIBRATION_INTERVAL_HOURS = 24
DIAGNOSIS_POLL_INTERVAL_MINUTES = 15

ALERT_LOG_PATH = str(Path(__file__).resolve().parents[2] / "logs" / "alerts.jsonl")
ALERT_WEBHOOK_URL_ENV = "SUPERVISOR_ALERT_WEBHOOK_URL"
ALERT_WEBHOOK_TIMEOUT_S = 10.0

ALERT_EMAIL_SMTP_HOST_ENV = "SUPERVISOR_ALERT_EMAIL_SMTP_HOST"
ALERT_EMAIL_SMTP_PORT_ENV = "SUPERVISOR_ALERT_EMAIL_SMTP_PORT"
ALERT_EMAIL_SMTP_USER_ENV = "SUPERVISOR_ALERT_EMAIL_SMTP_USER"
ALERT_EMAIL_SMTP_PASSWORD_ENV = "SUPERVISOR_ALERT_EMAIL_SMTP_PASSWORD"
ALERT_EMAIL_TO_ENV = "SUPERVISOR_ALERT_EMAIL_TO"
ALERT_EMAIL_DEFAULT_SMTP_PORT = 465
ALERT_EMAIL_TIMEOUT_S = 10.0
