"""Tests for dynamiq.models.rc_model — to be filled in once simulate()
and calibrate() are implemented.

Planned cases:
    - simulate() with zero exogenous input holds temperature constant.
    - simulate() under a positive T_ext - T_zone gradient warms the zone.
    - calibrate() recovers known (r_wall, r_window, c_zone) from data
      generated by simulate() with those same parameters (RMSE ~ 0).
"""


def test_placeholder() -> None:
    assert True
