"""Agent 1 as a LangGraph agentic loop.

Turns the former one-shot pipeline (extract -> normalize -> persist) into a
loop that can notice low-confidence room extractions and dispatch follow-up
Groq calls (zoom, scale, adjacency, recount) before persisting, budgeted so
it can't loop forever.

Deviations from the original spec, made deliberately to match the *actual*
live system (verified against the real Supabase schema and the already-
shipped frontend contract this session — see repo history):

- ``rooms.building_id`` does not exist in the live `rooms` table (confirmed
  via a live query) — this graph never writes it. `Room` rows are scoped to
  a building only via `floor_id`.
- The frontend already sends a continuous compass angle, not a
  "top"/"bottom"/"left"/"right" string — the state field holding it is named
  `north_angle_deg` (not `north_direction`, which the original spec listed)
  to say honestly what it holds. `geometry_processor.compute_cardinal_orientations`
  already expects this float.
- `room_id` is generated by the existing, collision-safe
  `geometry_processor.auto_number_and_map_rooms` (`{building_id}-floor-{level}-room-{seq}`),
  not the spec's `{floor_level}{seq:02d}` scheme, which collides across
  buildings sharing a floor level (a real bug fixed earlier this session).
- Room-to-room adjacency isn't produced anywhere upstream (vision_processor
  and geometry_processor only know each room's own walls, not its
  neighbors). `_infer_bbox_adjacencies` below fills this gap with a simple
  geometric touching-bbox heuristic so `sanity_gate`'s adjacency check and
  the `room_adjacencies` persistence requirement have real data to work
  with, instead of being permanently inapplicable.
"""

from __future__ import annotations

import io
import json
import logging
import os
import re
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Literal, TypedDict

import httpx
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from sqlalchemy import JSON, Column
from sqlmodel import Field, SQLModel

from .db_manager import save_floor, save_room
from .geometry_processor import auto_number_and_map_rooms, compute_cardinal_orientations
from .plan_annotator import _load_source_image
from .schema_models import Floor, Room, default_room_config
from .vision_processor import (
    GROQ_API_URL,
    RETRY_AFTER_PATTERN,
    _call_groq_vision,
    _downscale_to_base64_jpeg,
)

logger = logging.getLogger(__name__)

CEILING_HEIGHT_M = 3.2
INITIAL_BUDGET = 5
LOW_CONFIDENCE_THRESHOLD = 0.7
DECISION_MODEL = "llama-3.3-70b-versatile"


# ── building_agent_runs table ────────────────────────────────────────────
# Owns its own table definition (not schema_models.py) per this feature's
# file-scope: graph.py is meant to be self-contained so the rest of the
# package stays untouched.

BUILDING_AGENT_RUNS_DDL = """
CREATE TABLE IF NOT EXISTS public.building_agent_runs (
    run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    building_id varchar,
    floor_id varchar,
    started_at timestamptz,
    finished_at timestamptz,
    iterations integer,
    rooms_detected integer,
    rooms_saved integer,
    rooms_flagged integer,
    final_decision varchar,
    groq_model varchar,
    extraction_raw_count integer,
    iteration_number integer,
    gate_low_confidence_rooms jsonb,
    gate_scores jsonb,
    gate_decision varchar,
    gate_budget_remaining integer,
    tool_chosen varchar,
    tool_target varchar,
    tool_before jsonb,
    tool_after jsonb,
    run_log jsonb
);
"""


class BuildingAgentRun(SQLModel, table=True):
    __tablename__ = "building_agent_runs"  # type: ignore[assignment]

    run_id: str = Field(primary_key=True)
    building_id: str | None = None
    floor_id: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None
    iterations: int | None = None
    rooms_detected: int | None = None
    rooms_saved: int | None = None
    rooms_flagged: int | None = None
    final_decision: str | None = None
    groq_model: str | None = None
    extraction_raw_count: int | None = None
    iteration_number: int | None = None
    gate_low_confidence_rooms: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    gate_scores: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    gate_decision: str | None = None
    gate_budget_remaining: int | None = None
    tool_chosen: str | None = None
    tool_target: str | None = None
    tool_before: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    tool_after: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    run_log: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))


def ensure_building_agent_runs_table(engine) -> None:
    """Create building_agent_runs if it doesn't exist yet. Safe to call repeatedly."""

    with engine.begin() as conn:
        conn.exec_driver_sql(BUILDING_AGENT_RUNS_DDL)


# ── state ─────────────────────────────────────────────────────────────────


class _BuildingAgentInput(TypedDict):
    """Fields always present from the moment `run_graph` seeds the initial
    state — guaranteed, so accessing them with state["key"] is safe."""

    file_bytes: bytes
    filename: str
    north_angle_deg: float
    building_id: str
    floor_level: int
    api_key: str


class BuildingAgentState(_BuildingAgentInput, total=False):
    """Everything else accumulates as the graph runs — a given node can't
    statically prove these are set yet, so access them with .get() inside
    node bodies rather than state["key"]."""

    floor_name: str | None
    expected_room_count: int | None
    rooms: list[dict[str, Any]]
    budget_remaining: int
    iteration: int
    low_confidence_rooms: list[str]
    gate_failed_checks: dict[str, list[str]]
    gate_decision: Literal["persist", "flag", "decide"]
    chosen_tool: Literal["zoom", "scale", "adjacency", "recount"] | None
    tool_target: str | None
    saved_rooms: list[str]
    flagged_rooms: list[str]
    # Bookkeeping carried through the loop for the final building_agent_runs row.
    run_id: str
    run_log: list[dict[str, Any]]
    extraction_raw_count: int
    groq_model: str
    oriented_walls: dict[str, str]
    floor: Any  # persisted Floor ORM row, set by `persist`


def _log_event(state: BuildingAgentState, **event: Any) -> None:
    state.setdefault("run_log", []).append({"at": datetime.now(timezone.utc).isoformat(), **event})


# ── geometric adjacency inference ────────────────────────────────────────
# geometry_processor only knows each room's own wall->cardinal mapping, not
# which room sits on the other side of a given wall. This fills that gap
# with a cheap touching-bbox heuristic in normalized image space.

_TOUCH_EPSILON = 0.02  # normalized units; bboxes within this gap count as touching


def _infer_bbox_adjacencies(rooms: list[dict[str, Any]]) -> list[tuple[str, str, str, float]]:
    """Return (room_id_a, room_id_b, direction_of_b_relative_to_a, overlap) for touching rooms.

    `overlap` (the shared-edge length) lets callers pick the strongest
    neighbor when a room touches more than one along the same side.
    """

    pairs: list[tuple[str, str, str, float]] = []
    for i, a in enumerate(rooms):
        ab = a["bbox"]
        ax0, ay0 = ab["x"], ab["y"]
        ax1, ay1 = ax0 + ab["width"], ay0 + ab["height"]
        for b in rooms[i + 1 :]:
            bb = b["bbox"]
            bx0, by0 = bb["x"], bb["y"]
            bx1, by1 = bx0 + bb["width"], by0 + bb["height"]

            vertical_overlap = min(ay1, by1) - max(ay0, by0)
            horizontal_overlap = min(ax1, bx1) - max(ax0, bx0)

            if vertical_overlap > 0 and abs(bx0 - ax1) <= _TOUCH_EPSILON:
                pairs.append((a["room_id"], b["room_id"], "east", vertical_overlap))
            elif vertical_overlap > 0 and abs(ax0 - bx1) <= _TOUCH_EPSILON:
                pairs.append((a["room_id"], b["room_id"], "west", vertical_overlap))
            elif horizontal_overlap > 0 and abs(by0 - ay1) <= _TOUCH_EPSILON:
                pairs.append((a["room_id"], b["room_id"], "south", horizontal_overlap))
            elif horizontal_overlap > 0 and abs(ay0 - by1) <= _TOUCH_EPSILON:
                pairs.append((a["room_id"], b["room_id"], "north", horizontal_overlap))

    return pairs


_OPPOSITE = {"north": "south", "south": "north", "east": "west", "west": "east"}


def _apply_adjacencies(rooms: list[dict[str, Any]]) -> None:
    """Write inferred neighbor room_ids into each room's config_json.adjacency, in place.

    A room can touch more than one neighbor along the same side (e.g. a
    large office bordering several smaller rooms) — resolve each
    (room, direction) slot to the single strongest (largest-overlap)
    neighbor first, instead of applying pairs in list order. Verified live:
    without this, whichever pair happened to be processed last silently
    overwrote an earlier one, leaving the discarded neighbor still pointing
    back — sanity_gate's adjacency_consistency check then flagged both
    rooms permanently, and no tool (least of all "zoom", which only
    touches area) could ever fix it, burning the whole retry budget.
    """

    by_id = {r["room_id"]: r for r in rooms}
    best: dict[tuple[str, str], tuple[str, float]] = {}
    for room_a_id, room_b_id, direction, overlap in _infer_bbox_adjacencies(rooms):
        a_key = (room_a_id, direction)
        if a_key not in best or overlap > best[a_key][1]:
            best[a_key] = (room_b_id, overlap)
        b_key = (room_b_id, _OPPOSITE[direction])
        if b_key not in best or overlap > best[b_key][1]:
            best[b_key] = (room_a_id, overlap)

    for (room_id, direction), (neighbor_id, _overlap) in best.items():
        room = by_id[room_id]
        room.setdefault("config_json", default_room_config())
        room["config_json"].setdefault("adjacency", {})[direction] = neighbor_id


# ── Groq helpers specific to this graph ──────────────────────────────────
# Vision calls reuse vision_processor's tuned request shape (downscale size,
# reasoning_effort="none", 429 retry) rather than re-deriving it — that
# tuning came from real rate-limit debugging earlier this session.


def _crop_room_bytes(file_bytes: bytes, filename: str, bbox: dict[str, float]) -> bytes:
    image = _load_source_image(file_bytes, filename)
    width, height = image.size
    x0 = max(0, int(bbox["x"] * width) - 10)
    y0 = max(0, int(bbox["y"] * height) - 10)
    x1 = min(width, int((bbox["x"] + bbox["width"]) * width) + 10)
    y1 = min(height, int((bbox["y"] + bbox["height"]) * height) + 10)
    crop = image.crop((x0, y0, x1, y1))
    buffer = io.BytesIO()
    crop.save(buffer, format="PNG")
    return buffer.getvalue()


def _call_groq_vision_json(image_bytes: bytes, prompt: str, api_key: str) -> dict[str, Any]:
    image_b64 = _downscale_to_base64_jpeg(image_bytes)
    raw_text = _call_groq_vision(image_b64, "image/jpeg", api_key, prompt=prompt)
    parsed = _parse_groq_response_object(raw_text)
    return parsed


def _parse_groq_response_object(raw_text: str) -> dict[str, Any]:
    """Like vision_processor._parse_groq_response, but for a single JSON object."""

    text = re.sub(r"<think>.*?</think>", "", raw_text, flags=re.DOTALL).strip()
    text = re.sub(r"```(?:json)?", "", text).strip()
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            parsed = json.loads(match.group())
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass
    return {}


# Separate rate-limit budget from vision_processor's — this hits Groq's text
# model (llama-3.3-70b-versatile), not the vision model, so it has its own
# TPM allowance, but a busy minute can still 429 it just the same.
_DECISION_RATE_LIMIT_RETRIES = 5


def _call_groq_decision(prompt: str, api_key: str) -> dict[str, Any]:
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {
        "model": DECISION_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 400,
        "temperature": 0.1,
        "response_format": {"type": "json_object"},
    }
    with httpx.Client(timeout=60.0) as client:
        for attempt in range(_DECISION_RATE_LIMIT_RETRIES + 1):
            response = client.post(GROQ_API_URL, json=payload, headers=headers)

            if response.status_code == 429 and attempt < _DECISION_RATE_LIMIT_RETRIES:
                match = RETRY_AFTER_PATTERN.search(response.text)
                delay = float(match.group(1)) + 0.5 if match else 5.0
                logger.info("decide_action: rate limited, retrying in %.1fs", delay)
                time.sleep(delay)
                continue

            if response.is_error:
                raise ValueError(
                    f"Groq decision request failed with HTTP {response.status_code}: {response.text}"
                )

            content = response.json()["choices"][0]["message"]["content"]
            return _parse_groq_response_object(content)

    raise AssertionError("unreachable")  # loop always returns or raises


def _find_room(rooms: list[dict[str, Any]], room_id: str) -> dict[str, Any] | None:
    return next((r for r in rooms if r["room_id"] == room_id), None)


# ── nodes ─────────────────────────────────────────────────────────────────


def extract_initial(state: BuildingAgentState) -> dict[str, Any]:
    from .vision_processor import GROQ_VISION_MODEL, extract_rooms_from_file

    detected = extract_rooms_from_file(
        file_bytes=state["file_bytes"],
        filename=state["filename"],
        api_key=state["api_key"],
    )
    logger.info("extract_initial: rooms_detected=%d groq_model=%s", len(detected), GROQ_VISION_MODEL)
    _log_event(state, node="extract_initial", rooms_detected=len(detected), groq_model=GROQ_VISION_MODEL)
    return {
        "rooms": detected,
        "extraction_raw_count": len(detected),
        "groq_model": GROQ_VISION_MODEL,
        "budget_remaining": INITIAL_BUDGET,
        "iteration": 0,
    }


def geometry_process(state: BuildingAgentState) -> dict[str, Any]:
    oriented_walls = compute_cardinal_orientations(state["north_angle_deg"])
    enriched = auto_number_and_map_rooms(
        state.get("rooms", []), state["building_id"], state["floor_level"], oriented_walls
    )
    for room in enriched:
        room["volume_m3"] = float(room["area_m2"]) * CEILING_HEIGHT_M

    _apply_adjacencies(enriched)

    logger.info("geometry_process: rooms_enriched=%d", len(enriched))
    _log_event(state, node="geometry_process", rooms_enriched=len(enriched), oriented_walls=oriented_walls)
    return {"rooms": enriched, "oriented_walls": oriented_walls}


def sanity_gate(state: BuildingAgentState) -> dict[str, Any]:
    rooms = state.get("rooms", [])
    expected_count = state.get("expected_room_count")
    budget_remaining = state.get("budget_remaining", 0)

    # Floor-level checks — each either contributes a pass/fail to every
    # room's score, or is inapplicable (skipped) for all rooms if we don't
    # have the data to evaluate it.
    count_match: bool | None
    if expected_count is not None:
        count_match = len(rooms) == expected_count
    else:
        count_match = None  # inapplicable — nothing to compare against

    area_coherence: bool | None = None  # no per-floor expected area is collected anywhere upstream

    scores: dict[str, float] = {}
    failed_checks: dict[str, list[str]] = {}
    low_confidence: list[str] = []
    for room in rooms:
        checks_applicable = 0
        checks_passed = 0
        room_failed: list[str] = []

        if count_match is not None:
            checks_applicable += 1
            if count_match:
                checks_passed += 1
            else:
                room_failed.append("count_match")

        if area_coherence is not None:
            checks_applicable += 1
            if area_coherence:
                checks_passed += 1
            else:
                room_failed.append("area_coherence")

        adjacency = room.get("config_json", {}).get("adjacency", {})
        has_any_neighbor = any(v not in (None, "external") for v in adjacency.values())
        if has_any_neighbor:
            # Consistency check: every neighbor reference must point back.
            checks_applicable += 1
            consistent = True
            for direction, neighbor_id in adjacency.items():
                if neighbor_id in (None, "external"):
                    continue
                neighbor = _find_room(rooms, neighbor_id)
                if neighbor is None:
                    consistent = False
                    continue
                back = neighbor.get("config_json", {}).get("adjacency", {}).get(_OPPOSITE[direction])
                if back != room["room_id"]:
                    consistent = False
            if consistent:
                checks_passed += 1
            else:
                room_failed.append("adjacency_consistency")

        score = 1.0 if checks_applicable == 0 else checks_passed / checks_applicable
        scores[room["room_id"]] = round(score, 3)
        if score < LOW_CONFIDENCE_THRESHOLD:
            low_confidence.append(room["room_id"])
            failed_checks[room["room_id"]] = room_failed

    if not low_confidence:
        decision: Literal["persist", "flag", "decide"] = "persist"
    elif budget_remaining <= 0:
        decision = "flag"
    else:
        decision = "decide"

    logger.info(
        "sanity_gate: scores=%s failed_checks=%s decision=%s budget_remaining=%d",
        scores, failed_checks, decision, budget_remaining,
    )
    _log_event(
        state,
        node="sanity_gate",
        scores=scores,
        low_confidence_rooms=low_confidence,
        failed_checks=failed_checks,
        decision=decision,
        budget_remaining=budget_remaining,
    )
    return {
        "low_confidence_rooms": low_confidence,
        "gate_decision": decision,
        "gate_failed_checks": failed_checks,
    }


def route_from_sanity_gate(state: BuildingAgentState) -> str:
    # sanity_gate always sets this right before routing here — "flag" is a
    # safety-first fallback (never silently persist unreviewed data) in the
    # unreachable case it's somehow missing.
    return state.get("gate_decision", "flag")


DECISION_PROMPT_TEMPLATE = """You are helping verify an automated floor-plan room \
extraction. These rooms scored below the confidence threshold and need a follow-up \
check. Pick exactly one tool to run next.

Low-confidence rooms, each with which check(s) failed and its current adjacency data:
{rooms_json}

Match the tool to the failed check — this matters, using the wrong tool cannot fix \
the actual problem:
- Room failed "adjacency_consistency": use "adjacency". tool_target = \
"room_id_A:room_id_B" where room_id_B is the conflicting neighbor shown in that \
room's adjacency data.
- Room failed "count_match": the floor's total room count is wrong, not any one \
room's geometry — use "recount" (tool_target = "").
- Room failed "area_coherence": use "scale" (tool_target = that room_id).
- No failed check listed (score was low for another reason): use "zoom" \
(tool_target = that room_id).

Available tools:
- "zoom": re-examine a single room's cropped image region to correct its \
bounding box and area. tool_target = one room_id.
- "scale": re-examine the full plan for a scale bar or dimension labels to \
correct a room's area. tool_target = one room_id.
- "adjacency": re-examine the shared wall between two rooms to correct which \
rooms are adjacent. tool_target = "room_id_A:room_id_B".
- "recount": re-examine the full plan to check whether the total room count \
is right. tool_target = "" (not room-specific).

Already tried this run (do not repeat the same tool + tool_target — if it didn't \
raise the score last time, it won't this time either):
{history_json}

Respond with ONLY a JSON object with exactly these keys:
{{"chosen_tool": "zoom" | "scale" | "adjacency" | "recount", "tool_target": string, "reasoning": string}}
"""


def decide_action(state: BuildingAgentState) -> dict[str, Any]:
    low_confidence_ids = state.get("low_confidence_rooms", [])
    failed_checks = state.get("gate_failed_checks", {})
    low_confidence_rooms = [r for r in state.get("rooms", []) if r["room_id"] in low_confidence_ids]
    history = [
        {"chosen_tool": e.get("chosen_tool"), "tool_target": e.get("tool_target")}
        for e in state.get("run_log", [])
        if e.get("node") == "decide_action"
    ]
    prompt = DECISION_PROMPT_TEMPLATE.format(
        rooms_json=json.dumps(
            [
                {
                    "room_id": r["room_id"],
                    "room_label": r.get("room_label"),
                    "area_m2": r.get("area_m2"),
                    "bbox": r.get("bbox"),
                    "failed_checks": failed_checks.get(r["room_id"], []),
                    "adjacency": r.get("config_json", {}).get("adjacency", {}),
                }
                for r in low_confidence_rooms
            ]
        ),
        history_json=json.dumps(history),
    )

    decision = _call_groq_decision(prompt, state["api_key"])
    chosen_tool = decision.get("chosen_tool")
    tool_target = decision.get("tool_target")
    # The model occasionally returns tool_target as a list instead of the
    # requested string (observed live) — coerce defensively.
    if isinstance(tool_target, list):
        tool_target = ":".join(str(t) for t in tool_target)
    tool_target = str(tool_target) if tool_target is not None else ""

    if chosen_tool not in {"zoom", "scale", "adjacency", "recount"}:
        chosen_tool = "recount"  # safe fallback if the model returns something invalid

    new_budget = state.get("budget_remaining", INITIAL_BUDGET) - 1
    new_iteration = state.get("iteration", 0) + 1

    logger.info(
        "decide_action: chosen_tool=%s tool_target=%s reasoning=%s budget_remaining=%d",
        chosen_tool, tool_target, decision.get("reasoning"), new_budget,
    )
    _log_event(
        state,
        node="decide_action",
        chosen_tool=chosen_tool,
        tool_target=tool_target,
        reasoning=decision.get("reasoning"),
        budget_remaining=new_budget,
    )
    return {
        "chosen_tool": chosen_tool,
        "tool_target": tool_target,
        "budget_remaining": new_budget,
        "iteration": new_iteration,
    }


def route_from_decide(state: BuildingAgentState) -> str:
    return state.get("chosen_tool") or "recount"


ZOOM_PROMPT = """This is a cropped region of an architectural floor plan, centered \
on one room. Re-examine it and return ONLY a JSON object:
{"room_label": string, "area_m2": number, "bbox": {"x": number, "y": number, "width": number, "height": number}}
bbox is normalized 0.0-1.0 relative to THIS cropped image."""


def tool_zoom(state: BuildingAgentState) -> dict[str, Any]:
    room_id = state.get("tool_target") or ""
    rooms = state.get("rooms", [])
    room = _find_room(rooms, room_id)
    if room is None:
        logger.warning("tool_zoom: room %s not found, skipping", room_id)
        return {}

    before_area = room.get("area_m2")
    crop_bytes = _crop_room_bytes(state["file_bytes"], state["filename"], room["bbox"])
    result = _call_groq_vision_json(crop_bytes, ZOOM_PROMPT, state["api_key"])

    if "area_m2" in result:
        try:
            room["area_m2"] = float(result["area_m2"])
            room["volume_m3"] = room["area_m2"] * CEILING_HEIGHT_M
        except (TypeError, ValueError):
            pass

    logger.info("tool_zoom: room_id=%s area_before=%s area_after=%s", room_id, before_area, room.get("area_m2"))
    _log_event(state, node="tool_zoom", room_id=room_id, area_before=before_area, area_after=room.get("area_m2"))
    return {"rooms": rooms}


SCALE_PROMPT = """This is an architectural floor plan. Look for a scale bar or \
printed dimension labels (e.g. "10'-0\\"X11'-0\\""). Using them, re-estimate the \
area in square meters of the room labeled "{room_label}". Return ONLY a JSON object:
{"scale_factor_found": string, "area_m2": number}
scale_factor_found should describe what you used (e.g. a dimension label or "none found")."""


def tool_scale(state: BuildingAgentState) -> dict[str, Any]:
    room_id = state.get("tool_target") or ""
    rooms = state.get("rooms", [])
    room = _find_room(rooms, room_id)
    if room is None:
        logger.warning("tool_scale: room %s not found, skipping", room_id)
        return {}

    before_area = room.get("area_m2")
    full_image_bytes = state["file_bytes"]
    prompt = SCALE_PROMPT.format(room_label=room.get("room_label", room_id))
    result = _call_groq_vision_json(full_image_bytes, prompt, state["api_key"])

    if "area_m2" in result:
        try:
            room["area_m2"] = float(result["area_m2"])
            room["volume_m3"] = room["area_m2"] * CEILING_HEIGHT_M
        except (TypeError, ValueError):
            pass

    scale_factor = result.get("scale_factor_found")
    logger.info(
        "tool_scale: room_id=%s area_before=%s area_after=%s scale_factor=%s",
        room_id, before_area, room.get("area_m2"), scale_factor,
    )
    _log_event(
        state, node="tool_scale", room_id=room_id, area_before=before_area,
        area_after=room.get("area_m2"), scale_factor_found=scale_factor,
    )
    return {"rooms": rooms}


ADJACENCY_PROMPT = """This is a cropped region of an architectural floor plan \
showing the shared boundary between two rooms. Determine whether they are truly \
adjacent (share a wall) and if so, which cardinal-agnostic direction ("north", \
"south", "east", or "west" in image space, i.e. up/down/left/right) the second \
room is relative to the first. Return ONLY a JSON object:
{"adjacent": boolean, "direction_of_second_from_first": "north"|"south"|"east"|"west"|null}"""


def tool_adjacency(state: BuildingAgentState) -> dict[str, Any]:
    target = state.get("tool_target") or ""
    room_a_id, _, room_b_id = target.partition(":")
    rooms = state.get("rooms", [])
    room_a = _find_room(rooms, room_a_id)
    room_b = _find_room(rooms, room_b_id)
    if room_a is None or room_b is None:
        logger.warning("tool_adjacency: could not resolve target %r, skipping", target)
        return {}

    union_bbox = {
        "x": min(room_a["bbox"]["x"], room_b["bbox"]["x"]),
        "y": min(room_a["bbox"]["y"], room_b["bbox"]["y"]),
        "width": 0.0,
        "height": 0.0,
    }
    union_bbox["width"] = max(
        room_a["bbox"]["x"] + room_a["bbox"]["width"], room_b["bbox"]["x"] + room_b["bbox"]["width"]
    ) - union_bbox["x"]
    union_bbox["height"] = max(
        room_a["bbox"]["y"] + room_a["bbox"]["height"], room_b["bbox"]["y"] + room_b["bbox"]["height"]
    ) - union_bbox["y"]

    crop_bytes = _crop_room_bytes(state["file_bytes"], state["filename"], union_bbox)
    result = _call_groq_vision_json(crop_bytes, ADJACENCY_PROMPT, state["api_key"])

    direction = result.get("direction_of_second_from_first")
    is_adjacent = bool(result.get("adjacent"))

    room_a.setdefault("config_json", default_room_config())
    room_b.setdefault("config_json", default_room_config())
    if is_adjacent and direction in _OPPOSITE:
        # config_json.adjacency holds one neighbor per direction (required by
        # schema_models.Adjacency, which get_thermal_parameters validates
        # against) — a room touching several neighbors on the same side can
        # only have one slot "win". Overwriting unconditionally here silently
        # breaks a *different*, already-consistent pair sharing that slot,
        # which showed up live as a whack-a-mole: fixing room-08's adjacency
        # flipped room-03 from consistent to inconsistent, then fixing that
        # flipped another, never converging within budget. Only claim a slot
        # that's empty or already ours — never steal one from a real neighbor.
        a_adjacency = room_a["config_json"].setdefault("adjacency", {})
        b_adjacency = room_b["config_json"].setdefault("adjacency", {})
        if a_adjacency.get(direction) in (None, "external", room_b_id):
            a_adjacency[direction] = room_b_id
        else:
            logger.info(
                "tool_adjacency: not overwriting %s's existing %s neighbor %s with %s",
                room_a_id, direction, a_adjacency.get(direction), room_b_id,
            )
        opposite = _OPPOSITE[direction]
        if b_adjacency.get(opposite) in (None, "external", room_a_id):
            b_adjacency[opposite] = room_a_id
        else:
            logger.info(
                "tool_adjacency: not overwriting %s's existing %s neighbor %s with %s",
                room_b_id, opposite, b_adjacency.get(opposite), room_a_id,
            )
    else:
        # Model says not adjacent — clear any (possibly wrong) inferred link.
        for d, neighbor in list(room_a["config_json"].get("adjacency", {}).items()):
            if neighbor == room_b_id:
                room_a["config_json"]["adjacency"][d] = "external"
        for d, neighbor in list(room_b["config_json"].get("adjacency", {}).items()):
            if neighbor == room_a_id:
                room_b["config_json"]["adjacency"][d] = "external"

    logger.info(
        "tool_adjacency: room_a=%s room_b=%s direction_corrected=%s adjacent=%s",
        room_a_id, room_b_id, direction, is_adjacent,
    )
    _log_event(
        state, node="tool_adjacency", room_a=room_a_id, room_b=room_b_id,
        direction_corrected=direction, adjacent=is_adjacent,
    )
    return {"rooms": rooms}


RECOUNT_PROMPT = """Count every closed polygon in this floor plan that represents \
a room (including corridors, stairs, closets — any fully enclosed space). Return \
ONLY a JSON object:
{"exact_count": number, "room_labels": [string, ...]}"""


def tool_recount(state: BuildingAgentState) -> dict[str, Any]:
    old_count = len(state.get("rooms", []))
    result = _call_groq_vision_json(state["file_bytes"], RECOUNT_PROMPT, state["api_key"])
    raw_count = result.get("exact_count")

    rooms_added = 0
    rooms_removed = 0
    if raw_count is None:
        logger.info("tool_recount: model returned no usable count, leaving rooms unchanged")
        _log_event(state, node="tool_recount", old_count=old_count, new_count=None)
        return {}
    try:
        new_count = int(raw_count)
    except (TypeError, ValueError):
        logger.info("tool_recount: model returned no usable count, leaving rooms unchanged")
        _log_event(state, node="tool_recount", old_count=old_count, new_count=None)
        return {}

    diff = new_count - old_count
    if abs(diff) > 2:
        # Meaningful mismatch, but we don't have new rooms' geometry to add —
        # record it for the log/gate; actually growing/shrinking the list
        # would need bboxes the recount prompt doesn't ask for.
        if diff > 0:
            rooms_added = diff
        else:
            rooms_removed = -diff

    logger.info(
        "tool_recount: old_count=%d new_count=%s rooms_added=%d rooms_removed=%d",
        old_count, new_count, rooms_added, rooms_removed,
    )
    _log_event(
        state, node="tool_recount", old_count=old_count, new_count=new_count,
        rooms_added=rooms_added, rooms_removed=rooms_removed,
    )
    return {"expected_room_count": new_count}


def flag_for_review(state: BuildingAgentState) -> dict[str, Any]:
    rooms = state.get("rooms", [])
    low_confidence_ids = state.get("low_confidence_rooms", [])
    flagged: list[str] = []
    for room in rooms:
        if room["room_id"] not in low_confidence_ids:
            continue
        room.setdefault("config_json", default_room_config())
        room["config_json"]["needs_review"] = True
        room["config_json"]["review_reason"] = "low confidence score after exhausting tool-call budget"
        flagged.append(room["room_id"])

    logger.info("flag_for_review: flagged=%s", flagged)
    _log_event(state, node="flag_for_review", flagged=flagged)
    return {"rooms": rooms, "flagged_rooms": flagged}


def persist(state: BuildingAgentState) -> dict[str, Any]:
    from .config import engine
    from sqlmodel import Session

    building_id = state["building_id"]
    floor_level = state["floor_level"]
    floor_id = f"{building_id}-floor-{floor_level}"

    with Session(engine, expire_on_commit=False) as session:
        floor = save_floor(
            session,
            Floor(
                floor_id=floor_id,
                building_id=building_id,
                level=floor_level,
                name=state.get("floor_name"),
                north_angle_deg=state.get("north_angle_deg"),
                oriented_walls=state.get("oriented_walls"),
            ),
        )

        rooms = state.get("rooms", [])
        saved_ids: list[str] = []
        for room_data in rooms:
            room_config = room_data.get("config_json") or default_room_config()
            thermal = room_config.get("thermal", {})
            room = Room(
                room_id=room_data["room_id"],
                floor_id=floor_id,
                room_label=room_data["room_label"],
                room_type=str(room_data.get("room_type", "classroom")),
                area_m2=float(room_data["area_m2"]),
                volume_m3=float(room_data.get("volume_m3", room_data["area_m2"] * CEILING_HEIGHT_M)),
                primary_orientation=str(room_data.get("primary_orientation", "unknown")),
                r_wall=float(thermal.get("wall_r_value", 1.8)),
                c_zone=float(thermal.get("estimated_C_zone", 145000.0)),
                config_json=room_config,
            )
            save_room(session, room)
            saved_ids.append(room.room_id)

        adjacency_pairs = _infer_bbox_adjacencies(rooms)
        for room_a_id, room_b_id, direction, _overlap in adjacency_pairs:
            from .schema_models import RoomAdjacency

            session.merge(RoomAdjacency(room_id=room_a_id, adjacent_room_id=room_b_id, direction=direction))
            session.merge(
                RoomAdjacency(room_id=room_b_id, adjacent_room_id=room_a_id, direction=_OPPOSITE[direction])
            )
        session.commit()

        run_id = state.get("run_id") or str(uuid.uuid4())
        events = state.get("run_log", [])
        last_gate_event = next((e for e in reversed(events) if e.get("node") == "sanity_gate"), None)
        run_row = BuildingAgentRun(
            run_id=run_id,
            building_id=building_id,
            floor_id=floor_id,
            started_at=None,
            finished_at=datetime.now(timezone.utc),
            iterations=state.get("iteration", 0),
            rooms_detected=state.get("extraction_raw_count", len(rooms)),
            rooms_saved=len(saved_ids),
            rooms_flagged=len(state.get("flagged_rooms", [])),
            final_decision=state.get("gate_decision"),
            groq_model=state.get("groq_model"),
            extraction_raw_count=state.get("extraction_raw_count"),
            iteration_number=state.get("iteration", 0),
            gate_low_confidence_rooms=state.get("low_confidence_rooms", []),
            gate_scores=last_gate_event.get("scores", {}) if last_gate_event else {},
            gate_decision=state.get("gate_decision"),
            gate_budget_remaining=state.get("budget_remaining"),
            tool_chosen=state.get("chosen_tool"),
            tool_target=state.get("tool_target"),
            run_log={"events": events},
        )
        session.merge(run_row)
        session.commit()

    logger.info(
        "persist: rooms_saved=%d rooms_flagged=%d run_id=%s",
        len(saved_ids), len(state.get("flagged_rooms", [])), run_id,
    )
    return {
        "saved_rooms": saved_ids,
        "flagged_rooms": state.get("flagged_rooms", []),
        "run_id": run_id,
        "floor": floor,
    }


# ── graph assembly ────────────────────────────────────────────────────────

_graph_builder = StateGraph(BuildingAgentState)
_graph_builder.add_node("extract_initial", extract_initial)
_graph_builder.add_node("geometry_process", geometry_process)
_graph_builder.add_node("sanity_gate", sanity_gate)
_graph_builder.add_node("decide_action", decide_action)
_graph_builder.add_node("tool_zoom", tool_zoom)
_graph_builder.add_node("tool_scale", tool_scale)
_graph_builder.add_node("tool_adjacency", tool_adjacency)
_graph_builder.add_node("tool_recount", tool_recount)
_graph_builder.add_node("flag_for_review", flag_for_review)
_graph_builder.add_node("persist", persist)

_graph_builder.add_edge(START, "extract_initial")
_graph_builder.add_edge("extract_initial", "geometry_process")
_graph_builder.add_edge("geometry_process", "sanity_gate")

_graph_builder.add_conditional_edges(
    "sanity_gate",
    route_from_sanity_gate,
    {"persist": "persist", "flag": "flag_for_review", "decide": "decide_action"},
)
_graph_builder.add_conditional_edges(
    "decide_action",
    route_from_decide,
    {
        "zoom": "tool_zoom",
        "scale": "tool_scale",
        "adjacency": "tool_adjacency",
        "recount": "tool_recount",
    },
)
_graph_builder.add_edge("tool_zoom", "sanity_gate")
_graph_builder.add_edge("tool_scale", "sanity_gate")
_graph_builder.add_edge("tool_adjacency", "sanity_gate")
_graph_builder.add_edge("tool_recount", "sanity_gate")
_graph_builder.add_edge("flag_for_review", "persist")
_graph_builder.add_edge("persist", END)

building_graph = _graph_builder.compile(checkpointer=MemorySaver())
